import json
import os
from datetime import datetime
from pathlib import Path

from rich.table import Table

from ui.tui import console, print_log
from utils.drive import upload_directory
from utils.kkn import KKN
from utils.logger import get_logger
from utils.report import _collect_attendance_data, generate_html, generate_pdf
from utils.simaster import Simaster

log = get_logger("group_report")

REPORT_DIR = Path(os.getenv("REPORT_DIR", "reports"))


def _load_credentials() -> dict[str, str]:
  """Load SIMASTER_CREDENTIALS JSON secret/env: {username: password}."""
  raw = os.getenv("SIMASTER_CREDENTIALS")
  if not raw:
    log.error("SIMASTER_CREDENTIALS env var is not set — cannot generate group report")
    return {}
  try:
    creds = json.loads(raw)
    if not isinstance(creds, dict):
      log.error("SIMASTER_CREDENTIALS must be a JSON object {username: password}")
      return {}
    return creds
  except json.JSONDecodeError as e:
    log.error("SIMASTER_CREDENTIALS is not valid JSON: %s", e)
    return {}


def _build_group_summary_html(user_summaries: list[dict]) -> str:
  generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
  rows = []
  for u in user_summaries:
    status_color = "#a6e3a1" if u["status"] == "ok" else "#f38ba8"
    rows.append(
      f"<tr>"
      f"<td>{u['username']}</td>"
      f"<td>{u['total']}</td>"
      f"<td>{u['attended']}</td>"
      f"<td>{u['missed']}</td>"
      f"<td style='color:{status_color}'>{u['status']}</td>"
      f"<td>{u.get('error', '')}</td>"
      f"</tr>"
    )

  total_users = len(user_summaries)
  ok_users = sum(1 for u in user_summaries if u["status"] == "ok")
  total_records = sum(u["total"] for u in user_summaries)
  total_attended = sum(u["attended"] for u in user_summaries)

  return f"""<!DOCTYPE html>
<html lang="id"><head><meta charset="utf-8">
<title>Group KKN Summary — {generated_at}</title>
<style>
  body {{ font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; margin: 2rem; color: #1e1e2e; }}
  h1 {{ color: #89dceb; border-bottom: 2px solid #89dceb; padding-bottom: .3rem; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 1rem; }}
  th, td {{ border: 1px solid #cdd6f4; padding: 0.5rem 0.7rem; text-align: left; }}
  th {{ background: #181825; color: #cdd6f4; }}
  .cards {{ display: flex; gap: 2rem; margin: 1rem 0; }}
  .card {{ background: #f0f0f0; padding: 1rem 1.5rem; border-radius: 8px; }}
  .card .num {{ font-size: 1.8rem; font-weight: bold; color: #89dceb; }}
  footer {{ margin-top: 2rem; color: #6c7086; font-size: 0.8rem; }}
</style></head>
<body>
  <h1>Ringkasan Grup KKN</h1>
  <p>Dibuat: {generated_at}</p>
  <div class="cards">
    <div class="card"><div class="num">{total_users}</div>Anggota</div>
    <div class="card"><div class="num">{ok_users}</div>Berhasil</div>
    <div class="card"><div class="num">{total_records}</div>Total Sub-entri</div>
    <div class="card"><div class="num">{total_attended}</div>Hadir</div>
  </div>
  <h2>Per Anggota</h2>
  <table><thead><tr>
    <th>Username</th><th>Total</th><th>Hadir</th><th>Belum</th><th>Status</th><th>Catatan</th>
  </tr></thead><tbody>{"".join(rows)}</tbody></table>
  <footer>Generated by kkn-automation</footer>
</body></html>"""


async def _process_single_user(username: str, password: str, date_str: str) -> dict:
  """Login as one user, fetch logbook, generate their report. Returns summary dict."""
  result = {"username": username, "total": 0, "attended": 0, "missed": 0, "status": "ok", "error": ""}

  try:
    simaster = Simaster(username, password)
    session = await simaster.login(verbose=False)
    if not session:
      result["status"] = "login_failed"
      result["error"] = "login failed"
      log.error("Login failed for %s — skipping", username)
      return result

    kkn = KKN(session, simaster, autostart=True)
    if kkn.loader:
      await kkn.loader

    records = _collect_attendance_data(kkn.main_program, kkn.assisted_program)
    result["total"] = len(records)
    result["attended"] = sum(1 for r in records if r["attended"])
    result["missed"] = result["total"] - result["attended"]

    user_dir = REPORT_DIR / username / date_str
    timestamp = datetime.now().strftime("%H%M")
    html_path = user_dir / f"kkn-report-{timestamp}.html"
    pdf_path = user_dir / f"kkn-report-{timestamp}.pdf"

    generate_html(records, None, html_path, title_prefix=username)
    generate_pdf(records, None, pdf_path, title_prefix=username)

    await session.aclose()
    log.info("Report for %s: %d records (%d attended)", username, result["total"], result["attended"])
    return result

  except Exception as e:
    result["status"] = "error"
    result["error"] = str(e)
    log.error("Failed to process %s: %s", username, e, exc_info=True)
    return result


async def generate_group_reports() -> bool:
  """Generate per-user reports for all SIMASTER_CREDENTIALS + group summary + Drive upload."""
  creds = _load_credentials()
  if not creds:
    print_log("No credentials found in SIMASTER_CREDENTIALS — cannot generate group report", "ERROR")
    return False

  date_str = datetime.now().strftime("%Y-%m-%d")
  log.info("Starting group report for %d users", len(creds))

  summaries = []
  for username, password in creds.items():
    print(f"Processing {username}...")
    summary = await _process_single_user(username, password, date_str)
    summaries.append(summary)

  # Group summary PDF
  group_dir = REPORT_DIR / "group-summary"
  group_dir.mkdir(parents=True, exist_ok=True)
  group_html = _build_group_summary_html(summaries)
  group_html_path = group_dir / f"{date_str}-group-summary.html"
  group_pdf_path = group_dir / f"{date_str}-group-summary.pdf"

  try:
    with open(group_html_path, "w", encoding="utf-8") as f:
      f.write(group_html)
    from weasyprint import HTML as WeasyHTML

    WeasyHTML(string=group_html).write_pdf(str(group_pdf_path))
    log.info("Group summary written to %s", group_pdf_path)
  except Exception as e:
    log.error("Failed to write group summary: %s", e, exc_info=True)

  # Write group-result.json
  group_result_path = REPORT_DIR / "group-result.json"
  try:
    with open(group_result_path, "w", encoding="utf-8") as f:
      json.dump({"generated_at": datetime.now().isoformat(), "users": summaries}, f, indent=2, ensure_ascii=False)
  except Exception as e:
    log.error("Failed to write group-result.json: %s", e)

  # Print summary table
  table = Table(box=None, title="Group Report Summary")
  table.add_column("User")
  table.add_column("Total")
  table.add_column("Hadir")
  table.add_column("Status")
  for s in summaries:
    table.add_row(s["username"], str(s["total"]), str(s["attended"]), s["status"])
  console.print(table)

  # Drive upload
  if os.getenv("GDRIVE_FOLDER_ID") and os.getenv("GDRIVE_SERVICE_ACCOUNT_JSON"):
    for s in summaries:
      if s["status"] != "ok":
        continue
      user_dir = REPORT_DIR / s["username"] / date_str
      if user_dir.exists():
        upload_directory(user_dir, [s["username"], date_str])
    group_dir_path = REPORT_DIR / "group-summary"
    if group_dir_path.exists():
      upload_directory(group_dir_path, ["group-summary"])
  else:
    log.info("Drive not configured — reports kept locally in %s", REPORT_DIR)

  all_ok = all(s["status"] == "ok" for s in summaries)
  print_log(
    f"Group report done: {sum(1 for s in summaries if s['status'] == 'ok')}/{len(summaries)} users OK",
    "SUCCESS" if all_ok else "WARN",
  )
  return all_ok
